docker-images: count-image hello-image
# Command syntax is:
# docker build -t image-name:tag dockerfile-path
count-image:
	docker build -t count:v0.1 ./count
hello-image:
	docker build -t hello:v0.1 ./hello

